# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d40a76669c218203cc617aae412b90cc66aa77e57174d13a3923591782a56cf5ffc521961cf093f6e92742dadfbb9f7a4b69ea0a8457b685a1a79d9e46ac2f02

test:
  secret_key_base: e590ecd8c530a3dc3cc543bd3889bee1f7742763a9d695107db7bc996098d9e3f0194af8756f9e7b94a5b4b4f13e8f62192355ff06da0a3c03ad6be3c692e89d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
